print("Two little black birds")
print("Sitting on a wall,")
print("One called Peter,")
print("The other called Paul.")
print()
print("Fly away peter")
print("Fly away Paul,")
print()
print("Come back Peter")
print("Come back Paul.")
print("- The end")